---

- name: 'Run 10_SLES_register.yml'
  import_playbook: 10_SLES_register.yml

- name: 'Run playbook-all_nodes-zypper_ref_accept_keys.yml'
  import_playbook: playbook-all_nodes-zypper_ref_accept_keys.yml

- name: 'Run playbook-all_nodes-add_screenrc.yml'
  import_playbook: playbook-all_nodes-add_screenrc.yml

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-jenkins_server-add_Jenkins_repository.yml'
  import_playbook: playbook-jenkins_server-add_Jenkins_repository.yml

- name: 'Run playbook-jenkins_server-install_and_configure_jenkins.yml'
  import_playbook: playbook-jenkins_server-install_and_configure_jenkins.yml

- name: 'Run playbook-jenkins-agent01-install_docker.yml'
  import_playbook: playbook-jenkins-agent01-install_docker.yml

- name: 'Run playbook-jenkins-agent02-install_podman.yml'
  import_playbook: playbook-jenkins-agent02-install_podman.yml

- name: 'Run playbook-jenkins-agent03-install_k3s.yml'
  import_playbook: playbook-jenkins-agent03-install_k3s.yml
